version: "3.8"

services:
  database:
    image: postgres:15-alpine
    volumes:
      - ./pgdata_prod:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432

  app:
    image: python:3.11.2-apline
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env.docker
    environment:
      POSTGRES_HOST: database
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: uvicorn expenses_app:app --workers 4 --host ${APP_HOST} --port ${APP_PORT} --reload --reload-dir . --log-config=log_config.ini --log-level=info

