version: "3.8"

services:
  database:
    image: postgres:15
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432

  app:
    image: python:3.11.2
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/app
    env_file:
      - .env.docker
    environment:
      POSTGRES_HOST: database
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: alembic upgrade head

