[build]
dockerfilePath = "Dockerfile.backend"

[deploy]
startCommand = "uvicorn expenses_app:app --host 0.0.0.0 --port 8000 --log-config=log_config.ini"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5