[build]
builder = "NIXPACKS"
buildCommand = "pip install poetry && poetry install --no-dev"

[deploy]
numReplicas = 1
startCommand = "uvicorn expenses_app:app"
sleepApplication = false
restartPolicyType = "NEVER"