[build]
builder = "NIXPACKS"
buildCommand = "pip install poetry && poetry install --no-dev"

[deploy]
numReplicas = 1
startCommand = "uvicorn app:app --host=0.0.0.0 --port=80"
sleepApplication = false
restartPolicyType = "NEVER"