[build]
builder = "NIXPACKS"
buildCommand = "pip install poetry && poetry install --no-dev"

[deploy]
numReplicas = 1
startCommand = "uvicorn expenses_app:app --host 0.0.0.0 --port 8000 --log-config=log_config.ini"
sleepApplication = false
restartPolicyType = "NEVER"