"""migration

Revision ID: 7a9133b052b1
Revises: 36a7e36e07df
Create Date: 2023-10-23 16:13:50.499324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a9133b052b1'
down_revision: Union[str, None] = '36a7e36e07df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'accounts', ['id'])
    op.create_unique_constraint(None, 'categories', ['id'])
    op.create_unique_constraint(None, 'currencies', ['id'])
    op.create_unique_constraint(None, 'expenses', ['id'])
    op.create_unique_constraint(None, 'groups', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='unique')
    op.drop_constraint(None, 'expenses', type_='unique')
    op.drop_constraint(None, 'currencies', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_constraint(None, 'accounts', type_='unique')
    # ### end Alembic commands ###
